### ISSUE TITLE
Add Read Only GitHub permissions to staff

### ISSUE THREAD

**Issue by adelhelj** [CS467-OPM-Site/OPM#17]

**Comment by adelhelj** [comment]
If you are working on a Project that has NDA/IP, you don't need to do this. However, clearly mention that aspect of your Project in your Progress Reports and other assignment submissions.

Otherwise make sure you give all of the following GitHub users "Read" permission in your code repositories:

Yatin: highOnBits
Radhika: rads-1996
Gokul: gokulkeshav
Cheng: Cheng-97 
Samarendra: knightsamar
Here's how to add any user to GitHub repo: https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/managing-repository-settings/managing-teams-and-people-with-access-to-your-repository#inviting-a-team-or-person

**Comment by GPropersi** [comment]
Added staff.
