### ISSUE TITLE
Rest API Routes for Splash Page

### ISSUE THREAD

**Issue by GPropersi** [CS467-OPM-Site/OPM#32]
Generate backend Rest API routes for:

`/api/v1/users/register` - POST

and

`/api/v1/users/auth` - POST

Handle invalid HTTP methods, missing Bearer token, user details already in database, user details not found in database, missing `username` field in POST to register, `username` limits of 3-100 characters long.

**Comment by adelhelj** [comment]
Looking forward to hooking this up to the FE. Thanks Giovanni.
