### ISSUE TITLE
Generate User Home Page Rest API Routes

### ISSUE THREAD

**Issue by GPropersi** [CS467-OPM-Site/OPM#34]
Setup routes for user home page, including:

`/api/v1/projects` - GET, POST

`/api/v1/projects/{project_id}` - GET

`/api/v1/teams` - GET, POST

`/api/v1/teams/{team_id}` - GET, DELETE

`/api/v1/teams/{team_id}/members` - GET, POST

- [x] `/api/v1/projects` - GET
- [x] `/api/v1/projects` - POST
- [x] `/api/v1/projects/{project_id}` - GET
- [x] `/api/v1/teams` - GET
- [x] `/api/v1/teams` - POST
- [x] `/api/v1/teams/{team_id}` - GET
- [x] `/api/v1/teams/{team_id}` - DELETE
- [x] `/api/v1/teams/{team_id}/members` - GET
- [x] `/api/v1/teams/{team_id}/members` - POST
- [x] `/api/v1/teams/{team_id}/members/{memberID}` - DELETE

**Comment by GPropersi** [comment]
Not until this issue is closed unfortunately! Hoping this week.

**Comment by adelhelj** [comment]
Ok cool just checking

**Comment by GPropersi** [comment]
Pull Request #39 checks off the following:
- [x] `/api/v1/projects` - GET
- [x] `/api/v1/teams` - GET
- [x] `/api/v1/teams/{team_id}` - GET
- [x] `/api/v1/teams/{team_id}/members` - GET

**Comment by GPropersi** [comment]
Pull Request #42  checks off the following:


- [x] `/api/v1/projects` - POST
- [x] `/api/v1/teams` - POST
- [x] `/api/v1/teams/{team_id}/members` - POST

**Comment by GPropersi** [comment]
Pull Request #47 checks off the following:

- [x] `/api/v1/projects/{project_id}` - GET
- [x] `/api/v1/teams/{team_id}` - DELETE
- [x] `/api/v1/teams/{team_id}/members/{memberID}` - DELETE
